# Generated by Django 2.2 on 2021-06-10 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hunter_app', '0002_remove_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dob',
        ),
    ]
