# Generated by Django 2.2 on 2021-06-10 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hunter_app', '0004_auto_20210610_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_post',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user_post',
            name='state',
        ),
    ]
